window.DEFAULT_SETTINGS={id:'store',name:'فريق أوسكار البرمجي',englishName:'Oscar Software Team',description:'حلول برمجية احترافية لأعمالك',whatsapp:'970597603119',phone:'+970597603119',email:'',facebook:'',instagram:'',tiktok:'',website:'',address:'فلسطين',telegramBotUsername:'',p2pApiBase:'',currency:'₪',primary:'#087f69',accent:'#d0ee98',theme:'light',cardStyle:'rounded',heroTitle:'حلول برمجية\nتصنع الفرق.',heroText:'كل ما تحتاجه لتطوير أعمالك، في مكان واحد. اكتشف أنظمة ذكية تبسّط يومك وتمنحك وقتاً لما هو أهم.',heroButton:'استكشف التطبيقات',heroLink:'#/apps',heroImage:'hero.png',logo:'oscar-logo-symbol.png',favicon:'oscar-logo-symbol.png',sections:['categories','featured','latest','offers','bestsellers','suggested','why','testimonials','faq','contact'],hiddenSections:[],about:'نحن فريق أوسكار البرمجي، نطور تطبيقات وأنظمة تساعد أصحاب الأعمال على تنظيم أعمالهم اليومية. من المحاسبة ونقاط البيع إلى الحلول المخصصة، نصمم برامج عملية تناسب احتياجات نشاطك.',privacy:'يتم تحميل كتالوج المتجر المنشور من قاعدة البيانات، وتُرسل طلبات الشراء وإثباتات الدفع إلى نظام P2P الآمن للمراجعة. لا يُعتبر الدفع مقبولاً إلا بعد اعتماد الإدارة.',terms:'الأسعار والعروض قابلة للتعديل. رفع إثبات الدفع لا يعني قبول الدفع تلقائياً؛ يبقى الطلب قيد المراجعة حتى تعتمد الإدارة التحويل. تفاصيل كل برنامج تحدد نطاق الخدمة والتسليم والدعم.'};
window.CATEGORY_NAMES=['المحاسبة','نقاط البيع','إدارة المخزون','إدارة الشركات','إدارة المشتركين','الكهرباء والمولدات','المطاعم','المتاجر','الأنظمة التعليمية','الأنظمة الطبية','برامج مخصصة'];
window.CATEGORY_ICONS=['chart','cart','box','building','users','bolt','coffee','bag','book','heart','code'];
window.SERVICES=['تصميم وبرمجة تطبيقات الويب','أنظمة ERP وإدارة الشركات','أنظمة نقاط البيع POS','أنظمة المحاسبة','المتاجر الإلكترونية','أنظمة مخصصة حسب احتياجك','صيانة وتطوير الأنظمة','تصميم واجهات المستخدم','تحويل الأفكار إلى تطبيقات'];
window.WHY=['حلول برمجية احترافية','تصميم حديث وسهل الاستخدام','دعم فني يرافقك','تحديثات مستمرة','سرعة وأداء','على الجوال والكمبيوتر','حلول حسب احتياجك','دعم أوفلاين للأنظمة المتوافقة','أنظمة قابلة للتطوير'];
window.I18n={locale:'ar',messages:{ar:{home:'الرئيسية',apps:'التطبيقات',cart:'السلة',favorites:'المفضلة',account:'حسابي'},en:{home:'Home',apps:'Applications',cart:'Cart',favorites:'Favorites',account:'Account'}},t(key){return this.messages[this.locale][key]||key}};
window.seedStore=async function(){
 if(await DB.get('settings','store'))return;
 if(DB.canWriteCloud())await DB.put('settings',{...DEFAULT_SETTINGS});
};
