'use strict';
/* P2P extensions for the existing Oscar admin panel. */
(()=>{
 const A=window.Admin;if(!A)return;
 A.labels={...A.labels,orders:'طلبات الدفع',payment_methods:'طرق الدفع'};
 A.icons={...A.icons,orders:'bag',payment_methods:'tag'};
 const baseListPage=A.listPage.bind(A),baseLoadList=A.loadList.bind(A),baseDraw=A.drawList.bind(A),baseRow=A.rowCells.bind(A),baseSchema=A.schema.bind(A),baseEdit=A.edit.bind(A),baseSave=A.saveEditor.bind(A),baseAction=A.action.bind(A),baseSettings=A.settingsPage.bind(A),baseExport=A.exportCSV.bind(A);
 A.dashboard=async function(){
  const values=[['عدد التطبيقات',S.products.length,'code'],['عدد التصنيفات',S.categories.length,'box'],['التطبيقات المنشورة',S.products.filter(p=>p.status==='active').length,'check'],['التطبيقات المخفية',S.products.filter(p=>p.status==='hidden').length,'eye']];
  return `<div class="row between mb wrap"><div><h1 style="font-size:28px">لوحة فريق أوسكار البرمجي</h1><p>الإدارة متصلة مباشرة بقاعدة Turso الحالية.</p></div><button class="btn" data-action="admin-add" data-table="products">${icon('plus')} إضافة تطبيق</button></div><div class="stats">${values.map(([t,v,i])=>`<article class="stat"><div><p>${t}</p><strong>${esc(v)}</strong></div>${icon(i)}</article>`).join('')}</div><div class="hint mt">تفتح لوحة الإدارة فوراً، وتُحمّل طلبات الدفع وطرق الدفع عند فتح أقسامها حتى لا تتأخر الصفحة الرئيسية.</div><div class="row mt wrap"><a class="btn" href="#/admin/orders">مراجعة طلبات الدفع</a><a class="btn secondary" href="#/admin/payment_methods">إدارة طرق الدفع</a><a class="btn secondary" href="#/admin/products">إدارة التطبيقات</a><button class="btn secondary" data-action="admin-test-db">فحص قاعدة البيانات</button></div>`
 };
 A.listPage=function(){
  if(this.section==='payment_methods')return `<div class="admin-tools"><input id="admin-search" type="search" placeholder="بحث في طرق الدفع…"><select id="admin-filter"><option value="">كل الحالات</option><option value="active">مفعلة</option><option value="disabled">معطلة</option></select><span class="spacer"></span><button class="btn" data-action="admin-add" data-table="payment_methods">${icon('plus')} إضافة طريقة دفع</button></div><div id="admin-table"></div>`;
  if(this.section==='orders')return `<div class="admin-tools"><input id="admin-search" type="search" placeholder="بحث برقم الطلب أو العميل…"><select id="admin-filter"><option value="">كل الحالات</option>${Object.entries(P2P_STATUS).map(([v,t])=>`<option value="${v}">${t}</option>`).join('')}</select><span class="spacer"></span><button class="btn secondary" data-action="admin-export" data-table="orders">${icon('download')} تصدير CSV</button></div><div id="admin-table"></div>`;
  return baseListPage();
 };
 A.loadList=async function(){await this.require();let rows;try{if(this.section==='orders')rows=await P2PAPI.adminOrders();else if(this.section==='payment_methods')rows=await P2PAPI.adminPaymentMethods();else return baseLoadList();this.rows=rows;this.drawList()}catch(e){this.rows=[];this.drawList();$('#admin-table')?.insertAdjacentHTML('afterbegin',`<div class="hint mb">تعذر الاتصال بنظام P2P: ${esc(e.message)}. <a class="green" href="#/admin/settings">تحقق من اتصال قاعدة البيانات من الإعدادات</a>.</div>`)}};
 A.drawList=function(){
  if(!['orders','payment_methods'].includes(this.section))return baseDraw();
  let rows=this.rows.filter(r=>JSON.stringify(r,(k,v)=>['proof_image','image'].includes(k)?undefined:v).toLowerCase().includes(this.q.toLowerCase()));if(this.filter)rows=rows.filter(r=>r.status===this.filter);rows.sort((a,b)=>(b.created_at||b.updated_at||'').localeCompare(a.created_at||a.updated_at||''));const n=rows.length,pages=Math.max(1,Math.ceil(n/15));this.page=Math.min(this.page,pages);const page=rows.slice((this.page-1)*15,this.page*15);const headers=this.section==='orders'?['رقم الطلب','العميل / Telegram','التاريخ','الإجمالي','طريقة الدفع','الحالة','الإجراءات']:['طريقة الدفع','الترتيب','الحالة','آخر تحديث','الإجراءات'];$('#admin-table').innerHTML=n?`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${page.map(r=>`<tr>${this.rowCells(r).map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div><div class="row between mt"><small class="muted">${n} سجل</small>${pages>1?pagination(this.page,pages,'admin-page'):''}</div>`:empty(this.section==='orders'?'لا توجد طلبات دفع':'لا توجد طرق دفع','',false,this.icons[this.section]);
 };
 A.rowCells=function(r){
  if(this.section==='payment_methods'){const actions=`<div class="row"><button class="iconbtn" data-action="admin-edit" data-table="payment_methods" data-id="${esc(r.id)}">${icon('edit')}</button><button class="iconbtn" data-action="admin-delete" data-table="payment_methods" data-id="${esc(r.id)}">${icon('trash')}</button></div>`;return [`<div class="row">${r.image?`<img src="${esc(safeUrl(r.image))}" style="width:42px;height:42px;object-fit:contain;border-radius:8px">`:''}<strong>${esc(r.name)}</strong></div>`,Number(r.sort_order)||0,r.status==='disabled'?'<span class="muted">معطلة</span>':'<span class="pill">مفعلة</span>',r.updated_at?dateLabel(r.updated_at):'—',actions]}
  if(this.section==='orders'){const tg=r.telegram||{},proof=r.payment_proof||{};return [esc(r.id),`<div class="row">${tg.photo_url?`<img src="${esc(safeUrl(tg.photo_url))}" style="width:36px;height:36px;border-radius:50%;object-fit:cover">`:icon('user')}<div><b>${esc(tg.full_name||r.customer?.name||'عميل')}</b><br><small dir="ltr">${tg.telegram_username?'@'+esc(tg.telegram_username):''}${tg.telegram_id?' · '+esc(tg.telegram_id):''}</small></div></div>`,r.created_at?dateLabel(r.created_at):'—',esc(r.total+' '+r.currency),esc(r.payment_method_name||'—'),`<span class="pill status-${esc(r.status)}">${esc(p2pStatusLabel(r.status))}</span>`,`<button class="btn secondary small" data-action="admin-order" data-id="${esc(r.id)}">${icon('eye')} التفاصيل</button>`]}
  return baseRow(r)
 };
 A.schema=function(table,p){if(table==='payment_methods')return `${field('name','اسم طريقة الدفع',p.name||'','text',{required:true,full:true})}${field('description','وصف مختصر',p.description||'','textarea',{full:true,rows:2})}${field('payment_details','بيانات الدفع',p.payment_details||'','textarea',{required:true,full:true,rows:5,hint:'كل بيان في سطر، مثال: رقم المحفظة: 01000000000'})}${field('instructions','تعليمات التحويل',p.instructions||'','textarea',{full:true,rows:4})}${field('status','الحالة',p.status||'active','select',{options:[['active','مفعلة'],['disabled','معطلة']]})}${field('sort_order','ترتيب الظهور',p.sort_order||0,'number',{min:0,step:1})}`;return baseSchema(table,p)};
 A.edit=async function(table,id){
  if(table!=='payment_methods')return baseEdit(table,id);await this.require();const p=id?(await P2PAPI.adminPaymentMethods()).find(x=>x.id===id):{};if(id&&!p)throw new Error('طريقة الدفع غير موجودة');this.table=table;this.editing=p;this.images=p.image?[p.image]:[];openModal((id?'تعديل':'إضافة')+' — طريقة دفع',`<form id="editor-form"><div class="form-grid">${this.schema(table,p)}<div class="full"><label class="field"><span>${icon('image')} صورة / شعار طريقة الدفع</span><input id="editor-images" type="file" accept="image/jpeg,image/png,image/webp"></label><div class="image-manager" id="image-manager"></div><small class="muted">JPG / PNG / WEBP — يتم ضغط الصورة تلقائياً.</small></div></div><div class="form-actions"><button type="submit" class="btn">${icon('check')} حفظ طريقة الدفع</button><button type="button" class="btn secondary" data-action="close-modal">إلغاء</button></div><p class="error-text" id="editor-error"></p></form>`,true);this.drawImages();$('#editor-images').onchange=async e=>{const btn=$('#editor-form button[type=submit]');btn.disabled=true;try{this.images=[await compressImage(e.target.files[0])];this.drawImages()}catch(err){fail(err)}finally{btn.disabled=false;e.target.value=''}};$('#editor-form').onsubmit=e=>this.saveEditor(e)
 };
 A.saveEditor=async function(e){
  if(this.table!=='payment_methods')return baseSave(e);e.preventDefault();const btn=e.target.querySelector('button[type=submit]');btn.disabled=true;try{await this.require();const d=Object.fromEntries(new FormData(e.target)),p={...this.editing},now=new Date().toISOString(),row={id:p.id||DB.uuid(),name:String(d.name||'').trim(),image:this.images[0]||p.image||'',description:String(d.description||'').trim(),payment_details:String(d.payment_details||'').trim(),instructions:String(d.instructions||'').trim(),status:d.status==='disabled'?'disabled':'active',sort_order:Math.max(0,Number(d.sort_order)||0),created_at:p.created_at||now,updated_at:now};if(!row.name)throw new Error('اكتب اسم طريقة الدفع');if(!row.payment_details)throw new Error('اكتب بيانات الدفع');await P2PAPI.savePaymentMethod(row);await DB.audit(p.id?'تعديل طريقة دفع':'إضافة طريقة دفع',row.name);closeModal();await this.render('payment_methods');toast('تم حفظ طريقة الدفع')}catch(err){$('#editor-error').textContent=err.message;btn.disabled=false}
 };
 A.status=async function(id,newStatus){await this.require();if(!['processing','completed','cancelled'].includes(newStatus))return;await P2PAPI.status(id,newStatus);await this.loadList();toast('تم تحديث حالة الطلب')};
 A.action=async function(action,b){
  if(action==='admin-order'){await this.require();const o=await P2PAPI.adminOrder(b.dataset.id);return openP2PAdminOrder(o)}
  if(action==='admin-payment-approve'){await this.require();return confirmModal('قبول الدفع','هل تأكدت من وصول التحويل ومطابقة المبلغ؟',async()=>{await P2PAPI.approve(b.dataset.id);await this.render('orders');toast('تم قبول الدفع')})}
  if(action==='admin-payment-reject'){await this.require();return openRejectPayment(b.dataset.id)}
  if(action==='admin-proof-zoom'){const o=await P2PAPI.adminOrder(b.dataset.id);if(o.payment_proof?.proof_image)openModal('إثبات الدفع',`<img src="${esc(safeUrl(o.payment_proof.proof_image))}" alt="إثبات الدفع" style="width:100%;max-height:78vh;object-fit:contain">`,true);return}
  if(action==='admin-delete'&&b.dataset.table==='payment_methods'){return confirmModal('حذف طريقة الدفع','هل تريد حذف طريقة الدفع؟ لن يؤثر ذلك على الطلبات القديمة.',async()=>{await P2PAPI.deletePaymentMethod(b.dataset.id);await DB.audit('حذف طريقة دفع',b.dataset.id);await this.render('payment_methods');toast('تم حذف طريقة الدفع')})}
  return baseAction(action,b)
 };
 A.settingsPage=function(){const html=baseSettings();if(this.settingsTab!=='general')return html;return html.replace('<div class="hint full">تغيير العملة',`${field('telegramBotUsername','اسم مستخدم بوت تيليجرام',S.settings.telegramBotUsername||'','text',{full:true,hint:'بدون @ — يُستخدم لزر المتابعة عبر تيليجرام خارج التطبيق المصغر'})}${field('p2pApiBase','رابط خدمة الدفع P2P',S.settings.p2pApiBase||'','url',{full:true,hint:'اتركه فارغاً عند التشغيل المحلي المباشر على Turso، أو ضع رابط خدمة الدفع عند النشر الخارجي'})}<div class="hint full">تغيير العملة`)};
 A.exportCSV=async function(table){if(table!=='orders')return baseExport(table);const rows=await P2PAPI.adminOrders(),cols=[['id','رقم الطلب'],['created_at','التاريخ'],['customer_name','العميل'],['telegram_username','اسم مستخدم تيليجرام'],['telegram_id','معرف تيليجرام'],['total','الإجمالي'],['currency','العملة'],['payment_method_name','طريقة الدفع'],['sender_account_name','الحساب المحول منه'],['status_text','الحالة']];const out=rows.map(o=>({...o,customer_name:o.telegram?.full_name||o.customer?.name||'',telegram_username:o.telegram?.telegram_username||'',telegram_id:o.telegram?.telegram_id||'',sender_account_name:o.payment_proof?.sender_account_name||'',status_text:p2pStatusLabel(o.status)}));const csv=[cols.map(c=>csvCell(c[1])).join(','),...out.map(r=>cols.map(([k])=>csvCell(r[k])).join(','))].join('\r\n');downloadFile('\uFEFF'+csv,'oscar-p2p-orders.csv','text/csv;charset=utf-8');toast('تم تصدير طلبات الدفع')};
 function openRejectPayment(id){openModal('رفض الدفع',`<form id="reject-payment-form"><p class="small mb">اكتب سبب الرفض ليظهر للمستخدم.</p>${field('reason','سبب الرفض','','textarea',{required:true,full:true,rows:4})}<div class="form-actions"><button class="btn danger" type="submit">رفض الدفع</button><button class="btn secondary" type="button" data-action="close-modal">تراجع</button></div><p class="error-text"></p></form>`);$('#reject-payment-form').onsubmit=async e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));try{if(!String(d.reason||'').trim())throw new Error('سبب الرفض مطلوب');await P2PAPI.reject(id,String(d.reason).trim());closeModal();await A.render('orders');toast('تم رفض الدفع وإرسال السبب للمستخدم')}catch(err){e.target.querySelector('.error-text').textContent=err.message}}}
 function openP2PAdminOrder(o){const tg=o.telegram||{},proof=o.payment_proof||{};const statusButtons=o.status==='payment_review'?`<button class="btn" data-action="admin-payment-approve" data-id="${esc(o.id)}">قبول الدفع</button><button class="btn danger" data-action="admin-payment-reject" data-id="${esc(o.id)}">رفض الدفع</button>`:o.status==='payment_approved'?`<button class="btn" data-action="admin-set-processing" data-id="${esc(o.id)}">قيد التنفيذ</button>`:o.status==='processing'?`<button class="btn" data-action="admin-set-completed" data-id="${esc(o.id)}">مكتمل</button>`:'';openModal('طلب '+esc(o.id),`<div class="admin-order-detail"><div class="telegram-profile">${tg.photo_url?`<img src="${esc(safeUrl(tg.photo_url))}" alt="">`:icon('user')}<div><strong>${esc(tg.full_name||o.customer?.name||'عميل')}</strong><p dir="ltr">${tg.telegram_username?'@'+esc(tg.telegram_username):'—'} · ${esc(tg.telegram_id||'بدون Telegram')}</p></div></div><div class="invoice-mini mt"><div class="summary-line"><span>رقم الطلب</span><strong dir="ltr">${esc(o.id)}</strong></div><div class="summary-line"><span>الحالة</span><strong>${esc(p2pStatusLabel(o.status))}</strong></div>${o.items.map(i=>`<div class="summary-line"><span>${esc(i.product_name||i.name)} × ${i.quantity||1}</span><strong>${esc((i.subtotal??i.price)+' '+o.currency)}</strong></div>`).join('')}<div class="summary-line summary-total"><span>الإجمالي</span><strong>${esc(o.total+' '+o.currency)}</strong></div><div class="summary-line"><span>طريقة الدفع</span><strong>${esc(o.payment_method_name||'—')}</strong></div><div class="summary-line"><span>الحساب المحول منه</span><strong>${esc(proof.sender_account_name||'—')}</strong></div></div>${proof.proof_image?`<button class="proof-admin-image" data-action="admin-proof-zoom" data-id="${esc(o.id)}"><img src="${esc(safeUrl(proof.proof_image))}" alt="صورة إثبات الدفع"><span>اضغط لعرض الإثبات بالحجم الكامل</span></button>`:'<div class="hint">لم يرفع المستخدم إثبات دفع بعد.</div>'}${o.rejection_reason?`<div class="payment-rejected"><strong>سبب الرفض</strong><p>${esc(o.rejection_reason)}</p></div>`:''}<div class="row wrap mt">${statusButtons}</div></div>`,true)}
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;try{if(b.dataset.action==='admin-set-processing'){e.stopImmediatePropagation();await A.status(b.dataset.id,'processing');closeModal();await A.render('orders')}else if(b.dataset.action==='admin-set-completed'){e.stopImmediatePropagation();await A.status(b.dataset.id,'completed');closeModal();await A.render('orders')}}catch(err){fail(err)}},true);
})();
